[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
disconnectedSessionTTL = 600
websocketPingInterval = 20
maxMessageSize = 200

[browser]
gatherUsageStats = false
